core/urls.py
from django.urls import path
from .views import (
    HomeView,
    ProductDetail,
    ProductView,
    remove_a_quantity_from_cart,
    add_to_cart,
    remove_from_cart,
    OrderSummaryView,
    CheckoutView
)


app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('products/', ProductView.as_view(), name='products'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('product/<slug>/', ProductDetail.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-quantity-from-cart/<slug>/',
         remove_a_quantity_from_cart, name='remove-quantity-from-cart'),
    path('order-summary', OrderSummaryView.as_view(), name='order-summary'),
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


CATEGORY_CHOICES = (
    ('CA', 'Camiseta'),
    ('ES', 'Esporte'),
    ('SO', 'Social'),
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:product', kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse('core:add-to-cart', kwargs={'slug': self.slug})

    def get_remove_from_cart_url(self):
        return reverse('core:remove-from-cart', kwargs={'slug': self.slug})


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} de {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()
    

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    ordered = models.BooleanField(default=False)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

core/forms.py
from django import forms
from django_countries.fields import CountryField


PAYMENT_CHOICES = (
    ('PS', 'Pagseguro'),
    ('ML', 'Mercado Livre')
)


class CheckoutForm(forms.Form):
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Informe seu endereço'
    }))
    apartment_address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Informe o seu apartamento'
    }))
    country = CountryField(blank_label='- Selecione um país -')
    zip = forms.CharField()
    same_billing_address = forms.BooleanField(widget=forms.CheckboxInput())
    save_info = forms.BooleanField(widget=forms.CheckboxInput())
    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

core/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from .models import Item, OrderItem, Order
from django.views.generic import ListView, DetailView, View
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CheckoutForm


class HomeView(ListView):
    model = Item
    paginate_by = 10
    template_name = 'home.html'


class ProductView(ListView):
    model = Item
    paginate_by = 10
    template_name = 'products.html'


class ProductDetail(DetailView):
    model = Item
    template_name = 'product.html'


class CheckoutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context = {
            'form': CheckoutForm()
        }
        return render(request, 'checkout-page.html', context)


class OrderSummaryView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        try:
            context = {
                'order': Order.objects.get(user=request.user, ordered=False)
            }
            return render(request, 'order_summary.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, "Você não possui nenhum pedido ativo")
            return redirect('/')


@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        user=request.user,
        item=item,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, 'Produto atualizado.')
        else:
            messages.info(request, 'Produto adicionado.')
            order.items.add(order_item)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, 'Produto adicionado.')
    return redirect('core:order-summary')


@login_required
def remove_a_quantity_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                user=request.user,
                item=item,
                ordered=False
            )[0]
            if order_item.quantity == 1:
                order.items.remove(order_item)
                order_item.delete()
            else:
                order_item.quantity -= 1
                order_item.save()
            messages.info(request, 'Produto atualizado.')
            return redirect('core:order-summary')
        else:
            messages.info(request, 'O produto não está na lista de pedidos.')

    return redirect('core:home')


@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                user=request.user,
                item=item,
                ordered=False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, 'Produto removido dos pedidos.')
        else:
            messages.info(request, 'O produto não está adicionado ao pedido.')
            return redirect('core:product', slug=item.slug)
    else:
        messages.info(request, 'Não é um pedido associado a você.')
        return redirect('core:product', slug=item.slug)
    return redirect('core:product', slug=item.slug)

templates/base.html
{% include 'partials/header.html' %}

{% block content %}
{% endblock content %}
{% block extra_body %}
{% endblock %}

{% include 'partials/footer.html' %}

templates/home-page.html
{% extends 'base.html' %}

{% block content %}
  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Learn Bootstrap 4 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">
        
        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for item in object_list %}
            <div class="col-lg-3 col-md-6 mb-4">

              <!--Card-->
              <div class="card">

                <!--Card image-->
                <div class="view overlay">
                  <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/13.jpg" class="card-img-top"
                    alt="">
                  <a>
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>
                <!--Card image-->

                <!--Card content-->
                <div class="card-body text-center">
                  <!--Category & Title-->
                  <a href="" class="grey-text">
                    <h5>{{ item.get_category_display }}</h5>
                  </a>
                  <h5>
                    <strong>
                      <a href="" class="dark-grey-text">{{ item.title }}
                          <span class="badge badge-pill {{item.get_label_display}}-color">NEW</span>
                      </a>
                    </strong>
                  </h5>
<h5>
                  </strong>
                </h5>

                  <h4 class="font-weight-bold blue-text">
                    <strong>${{item.price}}</strong>
                  </h4>

                </div>
                <!--Card content-->

              <!--Card-->
              </div>

            </div>
          {% endfor %}

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>

          <li class="page-item active">
            <a class="page-link" href="#">1
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">3</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">4</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">5</a>
          </li>

          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
      <!--Pagination-->

    </div>
</main>

{% endblock content %}

templates/order_summary.html
{% extends 'base.html' %}

{% block content %}

<!--Main layout-->
<main class="mt-4 pt-5">
	<div class="container">

		<h1>Resumo do pedido</h1>	

		<div class="table-responsive text-nowrap">

			<table class="table">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Nome do item</th>
						<th scope="col">Preço</th>
						<th scope="col">Quantidade</th>
						<th scope="col">Preço final</th>
					</tr>
				</thead>
				<tbody>
					{% for item in order.items.all %}
					<tr>
						<th scope="row">{{ forloop.counter }}</th>
						<td>{{ item.item.title }}</td>
						<td>${{ item.item.price }}</td>
						<td>
							<a href="{% url 'core:remove-quantity-from-cart' item.item.slug %}">
								<i class="fa fa-minus"></i>
							</a>
							&nbsp;
							{{ item.quantity }}
							&nbsp;
							<a href="{% url 'core:add-to-cart' item.item.slug %}">
								<i class="fa fa-plus"></i>
							</a>
						</td>
						<td>R$
							{% if item.item.discount_price %}
								{{ item.get_total_discount_item_price }}
								<span class="badge badge-primary">(Desconto: R${{ item.get_amount_saved }})</span>
							{% else %}
								{{ item.get_total_item_price }}
							{% endif %}
						</td>
					</tr>
					{% empty %}
						<tr>
							<td colspan="5">Seu carro está vazio</td>
						</tr>
						<tr>
							<td colspan="5">
								<a href="/" class="btn btn-primary float-right">Continuar comprando</a>
							</td>
						</tr>
					{% endfor %}
					{% if order.items %}
						<tr>
							<td colspan="4"><strong>Valor total do pedido</strong></td>
							<td>R${{ order.get_total }}</td>
						</tr>
						<tr>
							<td colspan="5">
								<a href="{% url 'core:checkout' %}" class="btn btn-primary float-right">Realizar checkout</a>
							</td>
						</tr>
					{% endif %}
				</tbody>
			</table>

		</div>
	</div>
</main>

{% endblock content %}

templates/partials/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}

  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>

  {% include 'partials/nav.html' %}
  
  {% include 'partials/messages.html' %}

templates/partials/nav.html
{% load cart_template_tags %}
<!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'core:home' %}">
        <strong class="blue-text">DjangoShop</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% if '/' == request.path %}active{% endif %}">
            <a class="nav-link waves-effect" href="{% url 'core:home' %}">Home
            </a>
          </li>
          <li class="nav-item {% if '/products' in request.path %}active{% endif %}">
            <a class="nav-link waves-effect" href="{% url 'core:products' %}">Produtos</a>
          </li>
          <li class="nav-item {% if '/checkout' in request.path %}active{% endif %}">
            <a class="nav-link waves-effect" href="{% url 'core:checkout' %}">Checkout</a>
          </li>
        </ul>

        {% if request.user.is_authenticated %}
			<ul class="navbar-nav nav-flex-icons">
			  <li class="nav-item">
				  <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
					<span class="badge red z-depth-1 mr-1">{{ request.user|cart_item_count }}</span>
				  <i class="fas fa-shopping-cart"></i>
				  <span class="clearfix d-none d-sm-inline-block"> Cart </span>
				</a>
			  </li>
			  <li class="nav-item">
				  <a href="{% url 'account_logout' %}" class="nav-link waves-effect">
				  <span class="clearfix d-none d-sm-inline-block">Deslogar</span>
				</a>
			  </li>
			</ul>
        {% else %}
			<ul class="navbar-nav nav-flex-icons">
			  <li class="nav-item">
				  <a href="{% url 'account_login' %}" class="nav-link waves-effect">
				  <span class="clearfix d-none d-sm-inline-block">Login</span>
				</a>
			  </li>
			  <li class="nav-item">
				  <a href="{% url 'account_signup' %}" class="nav-link waves-effect">
				  <span class="clearfix d-none d-sm-inline-block">Registrar</span>
				</a>
			  </li>
			</ul>
        {% endif %}

      </div>

    </div>
  </nav>

templates/partials/product/item.html
<div class="col-lg-3 col-md-6 mb-4">

              <!--Card-->
              <div class="card">

                <!--Card image-->
                <div class="view overlay">
                  <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/13.jpg" class="card-img-top"
                    alt="">
                  <a href="{{item.get_absolute_url}}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>
                <!--Card image-->

                <!--Card content-->
                <div class="card-body text-center">
                  <!--Category & Title-->
                  <a href="" class="grey-text">
                    <h5>{{ item.get_category_display }}</h5>
                  </a>
                  <h5>
                    <strong>
                      <a href="{{item.get_absolute_url}}" class="dark-grey-text">{{ item.title }}
                          <span class="badge badge-pill {{item.get_label_display}}-color">NEW teste</span>
                      </a>
                    </strong>
                  </h5>
<h5>
                  </strong>
                </h5>

                  <h4 class="font-weight-bold blue-text">
                    <strong>$
                        {% if item.discount_price %}
                            {{item.discount_price}}
                        {% else %}
                            {{item.price}}
                        {% endif %}
                    </strong>
                  </h4>

                </div>
                <!--Card content-->

              <!--Card-->
              </div>

            </div>

templates/product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{object.get_category_display}}</span>
              </a>
              <a href="">
                <span class="badge blue {{object.get_label_display}} mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
                <span class="mr-1">
                  <del>${{object.price}}</del>
                </span>
                <span>{{object.discount_price}}</span>
              {% else %}
                <span>${{object.price}}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{object.description}}</p>

            <!-- <form class="d-flex justify-content-left">
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> -->

				<a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p" type="submit">Adicionar ao carrinho
					<i class="fas fa-shopping-cart ml-1"></i>
				</a>

				<a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p" type="submit">Remover do carro
				</a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}